# Julia Basics

In [33]:
begin
    x=1
    y=2
    x+y
end
#result same without begin and end

3

In [90]:
(x=1;y=2;x+y)

3

# Strings

In [2]:
h = "Hello"
w = " World"
hi = h*w

"Hello World"

In [3]:
string(h,w)

"Hello World"

In [4]:
println(hi[begin])
#println(hi[end])
#println or print

H


In [5]:
"$h $w ! or smth else"
#$ variable string 

"Hello  World ! or smth else"

In [6]:
length(hi)

11

In [7]:
findfirst("Hello",hi) # show postion of string (solda yazilanin sagdaki stringdeki yeri)

1:5

In [10]:
findfirst("Baku", "Hello Baku from Warsaw")

7:10

In [12]:
occursin("Hello",hi) #there is this string - true or false

true

In [13]:
replace(hi,"World"=>"Warsaw")

"Hello Warsaw"

In [18]:
replace(hi,"World"=>"Warsaw")

"Hello Warsaw"

# Tuple

In [73]:
t = ("tuple",3,4.5,"end")

("tuple", 3, 4.5, "end")

In [74]:
typeof(t)

Tuple{String, Int64, Float64, String}

In [80]:
t[4]

"end"

In [82]:
#t[4] = "smth" -it is not working

LoadError: MethodError: no method matching setindex!(::Tuple{String, Int64, Float64, String}, ::String, ::Int64)

# Dictionary

In [62]:
d = Dict(5=>"A",4.5=>"B",4=>"C",3.5=>"D",3=>"E")

Dict{Real, String} with 5 entries:
  5   => "A"
  4   => "C"
  3.5 => "D"
  4.5 => "B"
  3   => "E"

In [68]:
# Add to Dict
 d[2] = "F"

"F"

In [64]:
d

Dict{Real, String} with 6 entries:
  5   => "A"
  4   => "C"
  3.5 => "D"
  2   => "F"
  4.5 => "B"
  3   => "E"

In [69]:
#Delete from Dict
pop!(d, 2)

"F"

In [71]:
d

Dict{Real, String}

In [81]:
#d[1] -it is not working 

LoadError: KeyError: key 1 not found

# Array

In [1]:
a1 = Array{Int64}(undef,5) #vector

5-element Vector{Int64}:
 1731235290512
          4946
            -1
             0
             0

In [2]:
a2 = Array{Int64}(undef,(2,2)) #2x2 matrix

2×2 Matrix{Int64}:
               0  1731230961904
 140711282000144              0

In [3]:
a3 = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [6]:
push!(a3,4)
#add elemet to array

4-element Vector{Int64}:
 1
 2
 3
 4

In [7]:
pop!(a3)
#delete element from end of array

4

In [4]:
a4 = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [39]:
a5 = [1 2 3; 0 10 100]

2×3 Matrix{Int64}:
 1   2    3
 0  10  100

In [41]:
randn(3)

3-element Vector{Float64}:
  0.9634738043570581
 -0.30189816146621395
 -0.135771502002226

In [42]:
rand(3) #number between 0 & 1

3-element Vector{Float64}:
 0.8659867471671021
 0.29814064871189283
 0.11161825529957714

In [49]:
rand(1,6) #number between 0 & 1

1×6 Matrix{Float64}:
 0.600294  0.676445  0.674655  0.62937  0.0597628  0.679281

In [50]:
round(31.5321)

32.0

In [53]:
rand(a1,2) #choose random (2)element from a1  

2-element Vector{Int64}:
   4294967326
 128849018909

In [57]:
size(a5)

(2, 3)

In [58]:
reshape(a5,(3,2))

3×2 Matrix{Int64}:
 1   10
 0    3
 2  100

# Set

In [84]:
a = Set([1,2,5,8])
b = Set([1,2,7,11])
print(a)
print(b)

Set([5, 2, 8, 1])Set([7, 2, 11, 1])

In [88]:
print(intersect(a,b)) #kesismesi
print(union(a,b))  #birlesmesi
print(setdiff(a,b)) #a-nin b-den ferqli elementler
print(setdiff(b,a)) #a-nin a-dan ferqli elementler

Set([2, 1])Set([5, 7, 2, 11, 8, 1])Set([5, 8])

# Loops

In [19]:
for i in 1:2:10 #= for i = 1 : 2 : 10

        println(i)
end

1
3
5
7
9


In [10]:
for i=1 : 3 , j = 7 : 9
    println(i,j)
end

17
18
19
27
28
29
37
38
39


In [26]:
m,n = 3,3
A =zeros(m,n)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [31]:
[i + j  for i in 1:m, j in 1:n]

#= 
for i in 1:m,j in 1:n
    A[i,j]= i + j 
end
A
=#

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

In [11]:
x=0
while x < 5 
    println(x)
    global x+=1
end

0
1
2
3
4


In [12]:
x=0
while true
    println(x)
    if x == 7 
        break
    end
    global x+=1
end

0
1
2
3
4
5
6
7


In [13]:
x = 0
while x<5
    global x+=1
    if x == 4
        continue
    end
    println(x)
end

1
2
3
5


In [23]:
for pesi in Pesiler
        println("Salam bir nomreli pesi $pesi")
end

Salam bir nomreli pesi Ali Khalil
Salam bir nomreli pesi Taleh
Salam bir nomreli pesi Behram
Salam bir nomreli pesi ƏLİ
Salam bir nomreli pesi Nurlan Cefer


In [24]:
Pesiler = ["Ali Khalil", "Taleh","Behram","ƏLİ","Nurlan Cefer"]

i = 1
while i<= length(Pesiler)
    pesi = Pesiler[i]
    println("Salam bir nomreli pesi $pesi")
    i+=1
end

Salam bir nomreli pesi Ali Khalil
Salam bir nomreli pesi Taleh
Salam bir nomreli pesi Behram
Salam bir nomreli pesi ƏLİ
Salam bir nomreli pesi Nurlan Cefer


In [14]:
[i^2 for i in [1,2,3,4,5]]

5-element Vector{Int64}:
  1
  4
  9
 16
 25

# Errors

In [19]:
for i in [1,9,16,-1]
    if i <0
        #throw(DomainError())
        error("You must write positive number")
    else
        println("i: $(sqrt(i))")
    end
end

i: 1.0
i: 3.0
i: 4.0


LoadError: You must write positive number

In [27]:
x = -9
try
    sqrt(x)
catch 
    println("You must write positive number")
end

You must write positive number


# Functions

In [29]:
function f(x,y)
    x+y
end

f(5,3)

8

In [30]:
f(x,y) = x^y
f(2,5)

32

In [33]:
function g(x,y)
    return x*y
    x+y
end

g(4,4)

16

In [48]:
function f(g1,g2)
    if (g1>g2)
        return("$g1 bigger")
    elseif (g1<g2)
        return("$g2 bigger")
    else
        return("$g1 equal $g2")
    end
end

f (generic function with 1 method)

In [51]:
# f(4,4)
# f(14,7)
# f(4,44)

In [57]:
d = [3,5,7,-4,10]
sort!(d)

5-element Vector{Int64}:
 -4
  3
  5
  7
 10

In [58]:
d

5-element Vector{Int64}:
 -4
  3
  5
  7
 10

after sort() d remain like previos  d = 3 5 7 -4 10

after sort!() d change  d = -4 3 5 7 10

# Conditional

In [ ]:
if x>y
    println("x greater than y")
elseif x<y
    println("x less than y")
else
    println("x = y")
end
    

In [97]:
(x < y ? "x less" : "x greater")

"x greater"

# Class 02.03.2023

In [1]:
#homeworku nece gondereceyeik? --Mail
#jupyterde yazilan kodu nece gondereceyik?
#another class time
#julia haqqinda cmd app jupyter
