# NumPy

In [3]:
import numpy as np

In [4]:
a = np.array([10,20,30],dtype = 'f')
b = np.array([[1,2,3],[10,20,30],[100,200,300]])
type(a)

numpy.ndarray

In [5]:
print(a)
print("**")
print(b)

[10. 20. 30.]
**
[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [6]:
print(a.ndim)
print(b.ndim)

1
2


In [7]:
A = np.arange(10,100,5)
A

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [14]:
C = A[(A>25) & (A<85)]
C


array([30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

In [23]:
D = A + 1 
D

array([11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91,
       96])

In [15]:
p = np.random.permutation(10)
i = np.random.randint(1,7)
print(p)
print(i)

[3 7 6 1 5 2 8 0 9 4]
4


In [16]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
a1 = np.round(np.random.rand(3,3))
a2 = np.round(np.random.rand(3,1))
a5 = np.round(np.random.rand(1,3))
a3 = np.hstack((a1,a2))
a4 = np.vstack((a1,a5))
print(a3)
print('-----------')
print(a4)

#np.sort(x)  or  x.sort()
# x = x[::1] desc

[[0. 1. 0. 0.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]]
-----------
[[0. 1. 0.]
 [1. 1. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


hstack / vstack   + sort

# Examples (SGH)

In [18]:
#Create a 10×10 matrix of zeros and then "frame" it with a border of ones.

x = np.ones((10, 10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [19]:
c = np.random.randint(10,size=(3, 3))
print(c)
print('Sum all',np.sum(c))
print('Sum columns',np.sum(c,axis=0))
print('Sum rows',np.sum(c,axis=1))

[[1 1 2]
 [2 3 1]
 [6 4 9]]
Sum all 29
Sum columns [ 9  8 12]
Sum rows [ 4  6 19]


In [20]:
#MAX and MIN values

array = np.random.randint(50, size=(5,5))  
print(array)
print('MIN: ',np.min(array))
print('MAX: ',np.max(array))


[[23 36  2 39 21]
 [47 16 35  1 26]
 [13 16  8 12  3]
 [47 23  7  9 22]
 [16 49 28 19 17]]
MIN:  1
MAX:  49


In [21]:
i = np.eye(5, 5)
i = i * np.random.randint(1, 100, (5, 5))
print(i)
 

[[55.  0.  0.  0.  0.]
 [ 0. 72.  0.  0.  0.]
 [ 0.  0. 64.  0.  0.]
 [ 0.  0.  0. 28.  0.]
 [ 0.  0.  0.  0. 83.]]
